version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
    ports:
      - "3306:3306"
    restart: unless-stopped
