name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Lint YAML
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml

      # Docker Compose config check
      - name: Docker Compose config check
        run: docker compose config

      # Kubernetes dry-run (ใช้ถ้ามีไฟล์ manifest k8s/)
      - name: Kubernetes dry-run
        run: |
          kubectl apply -f k8s/ --dry-run=client

      # Build Application (ตัวอย่าง แก้ตามโปรเจกต์จริง)
      - name: Build Application
        run: |
          echo "Building application..."
          # เช่น npm install && npm run build
